broker:
  type: rabbitmq
  username: "username"
  password: "password"
  port: 5672

bots:
  fish-java:
    image: "botica-bot-fishbowl-fish-java"
    lifecycle:
      type: proactive
      initialDelay: 5
      period: 5
    publish:
      key: "java_fish_movement"
      order: "move_fish"
    instances:
      fish_1:
        environment:
          - FISH_SILHOUETTE=1
          - FISH_POSITION_X=0
          - FISH_POSITION_Y=0
      fish_2:
        lifecycle:
          type: proactive
          initialDelay: 5
          period: 10
        environment:
          - FISH_SILHOUETTE=2
          - FISH_POSITION_X=5
          - FISH_POSITION_Y=5

  fish-node:
    image: "botica-bot-fishbowl-fish-node"
    lifecycle:
      type: proactive
      initialDelay: 5
      period: 5
    publish:
      key: "node_fish_movement"
      order: "move_fish"
    instances:
      fish_3:
        environment:
          - FISH_SILHOUETTE=3
          - FISH_POSITION_X=7
          - FISH_POSITION_Y=0

  manager:
    image: "botica-bot-fishbowl-manager"
    mount:
      - source: "./fishbowl"
        target: "/app/fishbowl"
        createHostPath: true
    lifecycle:
      type: reactive
      keys: [ "java_fish_movement", "node_fish_movement" ]
      order: "move_fish"
    instances:
      manager_1: { }

  pocket-cep:
    image: "pocket-cep"
    lifecycle:
      type: unmanaged
    instances:
      pocket-cep: { }

  cep-gateway:
    image: "botica-bot-cep-gateway"
    mount:
      - source: "./resources/cep-gateway.json"
        target: "/app/cep-gateway.json"
    lifecycle:
      type: reactive
      keys: [ "java_fish_movement", "node_fish_movement" ]
      order: "move_fish"
    instances:
      cep-gateway:
        environment:
          - CEP_GATEWAY_CONFIG_PATH=/app/cep-gateway.json
